# Generated by Django 4.2.7 on 2024-03-02 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("p_id", models.AutoField(primary_key=True, serialize=False)),
                ("p_name", models.CharField(max_length=50)),
                ("p_qty", models.IntegerField()),
                ("p_desc", models.CharField(max_length=200)),
                ("p_price", models.IntegerField()),
                ("poster", models.ImageField(null=True, upload_to="images/")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="category",
                        to="categories.category",
                    ),
                ),
            ],
        ),
    ]
