# Generated by Django 4.2.7 on 2024-03-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="poster", new_name="p_image",
        ),
    ]
